name: HEXO CI

on:
  push:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Configuration environment
        env:
          HEXO_DEPLOY_PRI: ${{secrets.HEXO_DEPLOY_PRI}}
        run: |
          mkdir -p ~/.ssh/
          echo "$HEXO_DEPLOY_PRI" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 700 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts
          git config --global user.name "Koios1143"
          git config --global user.email "ken1357924681010@gmail.com"
      - name: Install dependencies
        run: |
          cd webpage/
          npm i -g hexo-cli
          npm i -g hexo-math --save
          npm i -g hexo-deployer-git --save
          npm i -g hexo-excerpt --save
          npm i
      - name: Deploy hexo
        run: |
          cd webpage/
          hexo g
          hexo d
